spring:
    data:
        mongodb:
            database: result-management
            host: localhost
            port: 27017
            authentication-database: admin
#            username: root
#            password: root
    webflux:
        problemdetails:
            enabled: true

jwt:
    secretKey: ecf1222c-88fd-47f3-988f-bdd78bade1ad
